name: Updates E2E (dev client)

on:
  push:
    branches: [main, 'sdk-*']
    paths:
      - apps/expo-workflow-testing/.eas/workflows/updates-e2e-dev-client.yml
      - packages/expo-asset/**
      - packages/expo-manifests/**
      - packages/expo-updates-interface/**
      - packages/expo-updates/**
      - packages/expo-dev-client/**
      - packages/expo-dev-menu/**
      - packages/expo-dev-launcher/**
      - templates/expo-template-bare-minimum/**
  pull_request:
    paths:
      - apps/expo-workflow-testing/.eas/workflows/updates-e2e-dev-client.yml
      - packages/expo-asset/**
      - packages/expo-manifests/**
      - packages/expo-updates-interface/**
      - packages/expo-updates/**
      - packages/expo-dev-client/**
      - packages/expo-dev-menu/**
      - packages/expo-dev-launcher/**
      - templates/expo-template-bare-minimum/**
  schedule:
    - cron: '0 19 * * SUN' # 18:00 UTC every Sunday

concurrency:
  group: ${{ workflow.filename }}-${{ github.ref }}
  cancel_in_progress: true

defaults:
  tools:
    node: 22.22.0
    yarn: 1.22.22

jobs:
  ios:
    runs_on: macos-large
    image: latest
    steps:
      - name: Install applesimutils
        id: ios_simulator
        env:
          HOMEBREW_NO_AUTO_UPDATE: '1'
        run: |
          /opt/homebrew/bin/brew tap wix/brew
          /opt/homebrew/bin/brew install applesimutils
          xcrun simctl list
      - uses: eas/install_maestro
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Set up Updates E2E disabled project
        id: setup
        working_directory: ../..
        env:
          UPDATES_HOST: localhost
          UPDATES_PORT: '4747'
        run: |
          yarn --silent ts-node --transpile-only ./packages/expo-updates/e2e/setup/create-dev-client-eas-project.ts
          ls -la ../updates-e2e
      - name: Prepare E2E project
        id: prepare
        working_directory: ../../../updates-e2e
        run: |
          yarn generate-test-update-bundles ios test-update-1
          yarn ios:pod-install
      - name: Build E2E test app (debug)
        id: builddebug
        working_directory: ../../../updates-e2e
        run: |
          yarn maestro:ios:debug:build
      - uses: eas/start_ios_simulator
        with:
          device_identifier: iPhone 17
      - name: Start screen recording
        id: recordingstart
        working_directory: ../..
        run: |
          export RECORDINGS_HOME=$PWD
          set-output RECORDINGS_HOME "$RECORDINGS_HOME"
          echo "Recordings home at $RECORDINGS_HOME"
          SIMULATOR_UDIDS=$(xcrun simctl list -v devices booted -j | jq --raw-output '.devices | .[] | .[] | .udid')
          mkdir -p "$RECORDINGS_HOME/screen-recordings"

          for UDID in $(printf '%s\n' $SIMULATOR_UDIDS); do
            echo -n "Starting screen recording of simulator $UDID..."

            LOG_FILE="$RECORDINGS_HOME/screen-recordings/$UDID.log"
            PID_FILE="$RECORDINGS_HOME/screen-recordings/$UDID.pid"
            RECORDING_MOV="$RECORDINGS_HOME/screen-recordings/$UDID.mov"

            xcrun simctl io "$UDID" recordVideo -f $RECORDING_MOV > "$LOG_FILE" 2>&1 < /dev/null &
            RECORDING_PID=$!
            echo $RECORDING_PID > "$PID_FILE"
            echo "Log file at $LOG_FILE"

            i=0
            while [ $i -lt 20 ]; do
              if grep -q "Recording started" "$LOG_FILE"; then
                echo " done."
                break
              else
                sleep 1
                i=$((i+1))
              fi
            done

            if [ $i -eq 20 ]; then
              echo " failed (recording not started)."
              cat "$LOG_FILE"
            fi
          done
      - name: Run Maestro tests (debug)
        id: testdebug
        continue: true
        working_directory: ../../../updates-e2e
        run: |
          # start packager
          yarn start:dev-client
          ./maestro/maestro-test-executor.sh ./maestro/tests/updates-e2e-dev-client.yml ios debug || true
      - name: Stop screen recording
        id: recordingstop
        working_directory: ../..
        run: |
          SIMULATOR_UDIDS=$(xcrun simctl list -v devices booted -j | jq --raw-output '.devices | .[] | .[] | .udid')

          for UDID in $(printf '%s\n' $SIMULATOR_UDIDS); do
            echo -n "Stopping screen recording of simulator $UDID..."

            LOG_FILE="$RECORDINGS_HOME/screen-recordings/$UDID.log"
            PID_FILE="$RECORDINGS_HOME/screen-recordings/$UDID.pid"

            kill -2 $(cat $PID_FILE)

            i=0
            while [ $i -lt 20 ]; do
              if grep -q "Wrote video" "$LOG_FILE"; then
                break
              else
                sleep 1
                i=$((i+1))
              fi
            done

            if [ $i -eq 20 ]; then
              echo " failed (recording file busy)."
              continue
            fi

            echo " done."

            rm $LOG_FILE
            rm $PID_FILE
          done
      - name: Prepare screen recording
        id: recordingprepare
        working_directory: ../..
        run: |
          RECORDINGS_DIR="$RECORDINGS_HOME/screen-recordings"
          RECORDING_FILES=$(find "$RECORDINGS_DIR" -type f -print)
          set-output recording_files "$RECORDING_FILES"
          echo "Found:\n$RECORDING_FILES"
      - name: Upload screen recording
        id: recordingupload
        uses: eas/upload_artifact
        with:
          key: screen_recording
          path: ${{ steps.recordingprepare.outputs.recording_files }

  android:
    runs_on: linux-large-nested-virtualization
    image: latest
    steps:
      - uses: eas/install_maestro
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Set up Updates E2E disabled project
        id: setup
        working_directory: ../..
        env:
          UPDATES_HOST: localhost
          UPDATES_PORT: '4747'
        run: |
          yarn --silent ts-node --transpile-only ./packages/expo-updates/e2e/setup/create-dev-client-eas-project.ts
          ls -la ../updates-e2e
      - name: Prepare E2E project
        id: prepare
        working_directory: ../../../updates-e2e
        run: |
          yarn generate-test-update-bundles android test-update-1
      - uses: eas/start_android_emulator
        with:
          device_name: pixel_9
          system_image_package: system-images;android-34;default;x86_64
      - name: Build E2E test app (debug)
        id: builddebug
        working_directory: ../../../updates-e2e
        run: |
          yarn maestro:android:debug:build
      - name: Start packager
        id: startpackager
        working_directory: ../../../updates-e2e
        run: |
          yarn start:dev-client
      - name: Run Maestro test (debug) (load update through dev client)
        id: testdebug1
        working_directory: ../../../updates-e2e
        run: |
          ./maestro/maestro-test-executor.sh ./maestro/tests/devClient_runUpdate.yml android debug
